blank_issues_enabled: false
contact_links:
  - name: Ajuda ou Dúvidas
    url: https://github.com/jeanfbraga/Poligrafo/discussions
    about: Faça perguntas, tire dúvidas e converse com a comunidade no nosso fórum (Discussions).
